const usPresidents: string[] = [
  'George Washington',
  'John Adams',
  'Thomas Jefferson',
  'James Madison',
  'James Monroe',
  'John Quincy Adams',
  'Andrew Jackson',
  'Martin Van Buren',
  'William Henry Harrison',
  'John Tyler',
  'James Knox Polk',
  'Zachary Taylor',
  'Millard Fillmore',
  'Franklin Pierce',
  'James Buchanan',
  'Abraham Lincoln',
  'Andrew Johnson',
  'Hiram Ulysses Grant',
  'Rutherford Birchard Hayes',
  'James Abram Garfield',
  'Chester Alan Arthur',
  'Stephen Grover Cleveland',
  'Benjamin Harrison',
  'William McKinley',
  'Theodore Roosevelt',
  'William Howard Taft',
  'Thomas Woodrow Wilson',
  'Warren Gamaliel Harding',
  'John Calvin Coolidge',
  'Herbert Clark Hoover',
  'Franklin Delano Roosevelt',
  'Harry S. Truman',
  'Dwight David Eisenhower',
  'John Fitzgerald Kennedy',
  'Lyndon Baines Johnson',
  'Richard Milhous Nixon',
  'Gerald Rudolph Ford',
  'James Earl Carter',
  'Ronald Wilson Reagan',
  'George Herbert Walker Bush',
  'Willian Jefferson Clinton',
  'George Walker Bush',
  'Barack Hussein Obama',
  'Donald John Trump',
  'Joe Robinette Biden',
]

const sortedPresidents = [...usPresidents].sort()

export default sortedPresidents
